app/models.py
from sqlalchemy import Column, Integer, String, Float, DateTime, Date
from app.db import Base



class Watchlist(Base):
    __tablename__ = "watchlist"
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, nullable=False, unique=True)
    price = Column(Float, nullable = True)

class Price(Base):
    __tablename__ = "prices"
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, nullable=False)
    price = Column(Float, nullable=False)
    timestamp = Column(DateTime, nullable=False)

class JobRun(Base):
    __tablename__ = "jobs_run"
    id = Column(Integer, primary_key=True, index=True)
    job_name = Column(String, nullable=False)
    run_time = Column(DateTime, nullable=False)

class PriceHistory(Base):
    __tablename__ = "price_history"

    symbol = Column(String, primary_key=True)
    date = Column(Date, primary_key=True)

    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(Integer)

app/__init__.py
from flask import Flask
import os

from app.routes.core_routes import bp as core_bp
from app.routes.watchlist_routes import bp as watchlist_bp
from app.routes.movers_routes import bp as movers_bp
from app.routes.charts_routes import bp as charts_bp

def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "dev")

    app.register_blueprint(core_bp)
    app.register_blueprint(watchlist_bp)
    app.register_blueprint(movers_bp)
    app.register_blueprint(charts_bp)


    if not app.config.get("TESTING", False):
        from app.services.scheduler_service import start_scheduler
        start_scheduler()

    return app

app/routes.py
from flask import Blueprint, render_template, jsonify

bp = Blueprint("routes", __name__)

@bp.route("/")
def index():
    return render_template("base.html")

@bp.route("/health")
def health():
    return jsonify({"status": "ok"})

app/routes/__init__.py
from flask import Flask
from .core_routes import bp as core_bp
from .watchlist_routes import bp as watchlist_bp
from .movers_routes import bp as movers_bp
from .charts_routes import bp as charts_bp

def create_app():
    app = Flask(__name__)
    app.register_blueprint(core_bp)
    app.register_blueprint(watchlist_bp)
    app.register_blueprint(movers_bp)
    app.register_blueprint(charts_bp)

    return app

app/routes/charts_routes.py
from flask import Blueprint, render_template, request
from app.services.chart_service import plot_history_with_sma
from app.services.indicators_service import get_history_with_sma


bp = Blueprint("charts", __name__)

@bp.route("/charts", methods = ["POST"])
def show_charts():
    symbol = request.form.get("symbol")
    error = None
    image = None

    try:
        df = get_history_with_sma(symbol)

        if df is None or df.empty:
            error = f"No data available for {symbol}."
        else:
            image = plot_history_with_sma(df, symbol)

    except Exception as e:
        error=f"Could not load chart; {e}"

    return render_template("graphs.html", symbol=symbol, image=image, error=error)

app/routes/core_routes.py
from flask import Blueprint, jsonify, redirect

bp = Blueprint("routes", __name__)

@bp.route("/")
def index():
    return redirect("/watchlist")

@bp.route("/health")
def health():
    return jsonify({"status": "ok"})

app/routes/movers_routes.py
from flask import Blueprint, render_template
from app.services.movers_service import compute_movers
from app.db import SessionLocal
from app.models import Watchlist


bp = Blueprint("movers", __name__)

@bp.route("/movers", methods = ["GET"])
def show_movers():
    db = SessionLocal()
    movers={"top": [], "bottom": []}
    error = None

    try:
        #Currently hardcoded amount of movers to show for dashboard.
        symbols = [ w.symbol for w in db.query(Watchlist).all()]
        movers = compute_movers(symbols, 3)

    except Exception as e:
        error=f"Could not load movers; {e}"

    finally:
        db.close()

    return render_template("movers.html", movers=movers, error=error)

app/routes/watchlist_routes.py
from flask import Blueprint,  request, render_template, redirect, url_for, flash
from app.services.watchlist_service import add_symbol, delete_symbol
from app.services.price_service import latest_price

bp = Blueprint("watchlist", __name__)

#Add a ticker to the watchlist
@bp.route("/watchlist/add", methods=["POST"])
def add_watchlist():
    symbol = request.form.get("symbol")

    if not symbol:
        flash("Please enter a ticker symbol", "danger")
        return redirect(url_for("watchlist.watchlist_page"))

    result = add_symbol(symbol)

    if "error" in result:
        flash(result["error"], "danger")
    else:
        flash(result["message"], "success")


    return redirect(url_for("watchlist.watchlist_page"))

@bp.route("/watchlist/delete", methods=["POST"])
def delete_watchlist():
    symbol = request.form.get("symbol")
    result = delete_symbol(symbol)

    if "error" in result:
        flash(result["error"], "danger")
    else:
        flash(result["message"], "success")

    return redirect(url_for("watchlist.watchlist_page"))


from app.services.price_service import latest_price
from app.db import SessionLocal
from app.models import Watchlist

@bp.route("/watchlist", methods=["GET"])
def watchlist_page():
    session = SessionLocal()
    symbols = session.query(Watchlist).all()

    results = []
    for w in symbols:
        price, _ = latest_price(w.symbol)
        results.append({
            "symbol": w.symbol,
            "price": price
        })

    session.close()
    return render_template("watchlist.html", symbols=results)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>FinanceDashboard</title>
    </head>
    <body>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename = 'style.css')}}">

        <nav class="navbar">
            <div class="logo">FinanceDashboard</div>
            <ul class="nav-links">
                <li><a href="{{ url_for('watchlist.watchlist_page') }}">Watchlist</a></li>
                <li><a href="{{ url_for('movers.show_movers') }}">Movers</a></li>
            </ul>
        </nav>


        <main>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, msg in messages %}
                        <div class="alert alert-{{ category }} alert dismissible fade show" role="alert">
                        {{ msg }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock %}

            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

        </main>
    </body>
</html>

app/templates/graphs.html
{% extends "base.html" %}

{% block content %}
    {% if error %}
    <div class="alert alert-danger" role = "alert">
        {{ error }}
    </div>



    {% endif %}
    <div class="chart-container">
        <img src="{{ url_for('static', filename=image) }}" alt="{{ symbol }} chart">

    </div>
{% endblock %}

app/templates/movers.html
{% extends "base.html" %}

{% block content %}
    {% if error %}
    <div class="alert alert-danger" role = "alert">
        {{ error }}
    </div>
    {% endif %}
    <div class="container mt4">
        <h1 style="font-size: 24pt">Top Gains</h1>
        <table class = "table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Symbol</th>
                    <th>Latest Price</th>
                    <th>Previous Close</th>
                    <th>% Change</th>
                    <th>As of (CST)</th>
                </tr>
            </thead>
            <tbody>
                {% for row in movers.top %}
                    {% if row %}
                        <tr>
                            <td>{{ row.symbol}}</td>
                            <td>${{ "%.2f" | format(row.latest) }}</td>
                            <td>${{ "%.2f" | format(row.previous_close) }}</td>
                            <td>{{ "%.2f" | format(row.percent_change) }}%</td>
                            <td>{{ row.last_updated.strftime("%d/%m/%Y, %H:%M:%S") if row.last_updated else "NA" }}
                                {% if row.stale %}
                                    <span class="badge bg-warning">STALE</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5" class="text-danger text-center">No data available</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
        <h2 style="font-size: 24pt">Top Losers</h2>
        <table class = "table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Symbol</th>
                    <th>Latest Price</th>
                    <th>Previous Close</th>
                    <th>% Change</th>
                    <th>As of (CST)</th>
                </tr>
            </thead>
            <tbody>
                {% for row in movers.bottom %}
                    {% if row %}
                        <tr>
                            <td>{{ row.symbol }}</td>
                            <td>${{"%.2f" | format(row.latest) }}</td>
                            <td>${{"%.2f" | format(row.previous_close) }}</td>
                            <td>{{"%.2f" | format(row.percent_change)}}%</td>
                            <td>{{ row.last_updated.strftime("%d/%m/%Y, %H:%M:%S") if row.last_updated else "NA" }}
                                {% if row.stale %}
                                    <span class ="badge bg-warning">STALE</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5" class="text-danger text-center">No data available</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/watchlist.html
{% extends "base.html" %}

{% block content %}
    <form method= "POST" action ="{{ url_for('watchlist.add_watchlist') }}">
                        <input type="text" class="addtick" name = "symbol" id="symbol" pattern="[A-Z]{1,5}" placeholder="Enter Ticker" required >
                        <button type="submit" class="addtick" style="margin: 3px" name="symbol" id="symbol">Add Ticker</button>
                </form>

    <div class="container mt-4" style="background:rgb(0, 0, 120)">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Row</th>
                    <th>Symbol</th>
                    <th>Latest Price</th>
                    <th colspan="2">Actions</th>

                </tr>
            </thead>
            <tbody>
                {% for sym in symbols %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ sym.symbol }}</td>
                    <td>${{ "%.2f"|format(sym.price or 0) }}</td>
                    <td>
                        <form method = "POST" action="{{ url_for('watchlist.delete_watchlist') }}" class="d-inline">
                            <input type="hidden" name="symbol" value="{{ sym.symbol }}">
                            <button type="submit" class="btn btn-danger btn-sm" class="d-inline">Delete</button>
                        </form>
                        <form method = "POST" action="{{ url_for('charts.show_charts') }}" class="d-inline">
                            <input type="hidden" name="symbol" value="{{ sym.symbol }}">
                            <button type="submit" class="btn btn-danger btn-sm" class="d-inline">See Graph</button>
                        </form>
                    </td>

                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}